# Site settings
title: RelawanTIK Cilacap
email: info@rtikcilacap.or.id
author: relawan tik cilacap
tagline: "Tagline RTIK Cilacap apa ya..."
description: "Ada banyak variasi tulisan Lorem Ipsum yang tersedia, tapi kebanyakan sudah mengalami perubahan bentuk, entah karena unsur humor atau kalimat yang diacak hingga nampak sangat tidak masuk akal."
baseurl: ""
url: "http://rtikcilacap.or.id"
twitter_username: RTIKCilacap
github_username:  linuxsidareja

# Build settings
markdown: kramdown
permalink: /:title/
baseurl: /rtikcilacap
